### ISSUE TITLE
Incluir link do wayback machine no readme.md

### ISSUE THREAD

**Issue by Accorsi66** [RodrigoMenegat/autopsia-do-tratecov#3]
Aconselho adicionar a versão salva no dia 20/Jan por motivos de transparência e possuir o código na sua forma inalterada.

(Poderia abrir uma PR mas acho desnecessário)

https://web.archive.org/web/20210120031248/https://redcap.saude.gov.br/surveys/index.php?s=7M3XF79KFL

**Comment by RodrigoMenegat** [comment]
Adicionado [neste commit](https://github.com/RodrigoMenegat/autopsia-do-tratecov/commit/367d8d55c79a382e9250a40a344f4eae637bf512). Obrigado pela sugestão!
